[manifest]
version = "1.0.0"
priority = 0

#Adjusts The Duo to give X1.75 Mult
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
j_duo=              {order = 131,  unlocked = false, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 8, name = "The Duo", pos = {x=5,y=4}, set = "Joker", effect = "X1.5 Mult", cost_mult = 1.0, config = {Xmult = 2, type = 'Pair'}, unlock_condition = {type = 'win_no_hand', extra = 'Pair'}},
'''
position = 'at'
payload = '''
j_duo=              {order = 131,  unlocked = false, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 8, name = "The Duo", pos = {x=5,y=4}, set = "Joker", effect = "X1.5 Mult", cost_mult = 1.0, config = {Xmult = 1.75, type = 'Pair'}, unlock_condition = {type = 'win_no_hand', extra = 'Pair'}},
'''
match_indent = true