[manifest]
version = "1.0.0"
priority = 0

#Adjusts Tribe to give X2.5 Mult
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
j_tribe=            {order = 135,  unlocked = false, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 8, name = "The Tribe", pos = {x=9,y=4}, set = "Joker", effect = "X3 Mult", cost_mult = 1.0, config = {Xmult = 2, type = 'Flush'}, unlock_condition = {type = 'win_no_hand', extra = 'Flush'}},
'''
position = 'at'
payload = '''
j_tribe=            {order = 135,  unlocked = false, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 8, name = "The Tribe", pos = {x=9,y=4}, set = "Joker", effect = "X3 Mult", cost_mult = 1.0, config = {Xmult = 2.5, type = 'Flush'}, unlock_condition = {type = 'win_no_hand', extra = 'Flush'}},
'''
match_indent = true